# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nn_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nn_message.proto',
  package='neuralnet',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10nn_message.proto\x12\tneuralnet\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n\rMovementInput\x12\x10\n\x08rotation\x18\x01 \x01(\x01\x12\x10\n\x08northRay\x18\x02 \x01(\x01\x12\x14\n\x0cnorthwestRay\x18\x03 \x01(\x01\x12\x14\n\x0cnortheastRay\x18\x04 \x01(\x01\x12\x0f\n\x07\x65\x61stRay\x18\x05 \x01(\x01\x12\x10\n\x08southRay\x18\x06 \x01(\x01\x12\x0f\n\x07westRay\x18\x07 \x01(\x01\x12\x12\n\ndoorClosed\x18\x08 \x01(\x08\x12\x15\n\rcheckpointMet\x18\t \x01(\x05\x12\x1a\n\x12\x64istanceFromPlayer\x18\n \x01(\x01\x12\x0f\n\x07seesKey\x18\x0b \x01(\x08\"\xb1\x01\n\x0eMovementOutput\x12\x15\n\rmouseRotation\x18\x01 \x01(\x01\x12\x1c\n\x14\x66orwardButtonPressed\x18\x02 \x01(\x08\x12\x19\n\x11\x62\x61\x63kButtonPressed\x18\x03 \x01(\x08\x12\x19\n\x11leftButtonPressed\x18\x04 \x01(\x08\x12\x1a\n\x12rightButtonPressed\x18\x05 \x01(\x08\x12\x18\n\x10keyButtonPressed\x18\x06 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MOVEMENTINPUT = _descriptor.Descriptor(
  name='MovementInput',
  full_name='neuralnet.MovementInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotation', full_name='neuralnet.MovementInput.rotation', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='northRay', full_name='neuralnet.MovementInput.northRay', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='northwestRay', full_name='neuralnet.MovementInput.northwestRay', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='northeastRay', full_name='neuralnet.MovementInput.northeastRay', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eastRay', full_name='neuralnet.MovementInput.eastRay', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='southRay', full_name='neuralnet.MovementInput.southRay', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='westRay', full_name='neuralnet.MovementInput.westRay', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doorClosed', full_name='neuralnet.MovementInput.doorClosed', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpointMet', full_name='neuralnet.MovementInput.checkpointMet', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distanceFromPlayer', full_name='neuralnet.MovementInput.distanceFromPlayer', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seesKey', full_name='neuralnet.MovementInput.seesKey', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=300,
)


_MOVEMENTOUTPUT = _descriptor.Descriptor(
  name='MovementOutput',
  full_name='neuralnet.MovementOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mouseRotation', full_name='neuralnet.MovementOutput.mouseRotation', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forwardButtonPressed', full_name='neuralnet.MovementOutput.forwardButtonPressed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backButtonPressed', full_name='neuralnet.MovementOutput.backButtonPressed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leftButtonPressed', full_name='neuralnet.MovementOutput.leftButtonPressed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rightButtonPressed', full_name='neuralnet.MovementOutput.rightButtonPressed', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyButtonPressed', full_name='neuralnet.MovementOutput.keyButtonPressed', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=480,
)

DESCRIPTOR.message_types_by_name['MovementInput'] = _MOVEMENTINPUT
DESCRIPTOR.message_types_by_name['MovementOutput'] = _MOVEMENTOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MovementInput = _reflection.GeneratedProtocolMessageType('MovementInput', (_message.Message,), {
  'DESCRIPTOR' : _MOVEMENTINPUT,
  '__module__' : 'nn_message_pb2'
  # @@protoc_insertion_point(class_scope:neuralnet.MovementInput)
  })
_sym_db.RegisterMessage(MovementInput)

MovementOutput = _reflection.GeneratedProtocolMessageType('MovementOutput', (_message.Message,), {
  'DESCRIPTOR' : _MOVEMENTOUTPUT,
  '__module__' : 'nn_message_pb2'
  # @@protoc_insertion_point(class_scope:neuralnet.MovementOutput)
  })
_sym_db.RegisterMessage(MovementOutput)


# @@protoc_insertion_point(module_scope)
